name: CI/CD Pipeline

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # Specify the runner
    runs-on: ubuntu-latest

    # MongoDB service for tests
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check OpenSSL version
      run: |
          python -c "import ssl; print(ssl.OPENSSL_VERSION)"

    # Step 4: Run tests
    - name: Run tests
      env:
        MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}  # Use the MongoDB username secret
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}  # Use the MongoDB password secret
      run: |

        # Run tests
        pytest